services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0 
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env.local
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./mysql-db:/docker-entrypoint-initdb.d/
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
volumes:
  mysql-volume: