version: "3.9"
services:
  web:
    build: .
    ports:
      - "3306:3306" # Expose port 3000 on the host machine
    depends_on:
      - db 
  db:
    image: mysql:latest 
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employee
    volumes:
      - mysql_data:/var/lib/mysql 
volumes:
  mysql_data: